dist: trusty
sudo: required

language: python
python:
    - "2.7.10"
    - "3.6.4"

#virtualenv:
#    system_site_packages: true

before_install:
    - python -m pip install -U pip

install:
    - pip install -r src/main/python/requirements-dev.txt

before_script:
    - echo "" >> src/main/python/setup.cfg
    - echo "[egg_info]" >> src/main/python/setup.cfg
    - echo "tag_build=${TRAVIS_BUILD_NUMBER}" >> src/main/python/setup.cfg

script:
    - pyb -v clean publish
    - ls dist/dist -lat

notifications:
    email:
        - wesley.peng@live.com
