plugins:
    web:
        name                : SeleniumPlugin
        location            : ../plugins/web/selenium
        enabled             : True
    mobile:
        name                : AppiumPlugin
        location            : ../plugins/mobile/appium
        enabled             : False
    cli:
        name                : ParamikoPlugin
        location            : ../plugins/cli/paramiko
        enabled             : True
    REST:
        name                : RequestsPlugin
        location            : ../plugins/svc/requests
        enabled             : True