plugins:
    web:
        name                : SeleniumPlugin
        location            : ../plugins/web/selenium
        enabled             : True
    cli:
        name                : ParamikoPlugin
        location            : ../plugins/cli/paramiko
        enabled             : True